#!/usr/bin/env bash

if
  [[ -s "/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-1.8.7-p374/environment" ]]
then
  source "/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-1.8.7-p374/environment"
  exec rdebug-ide "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-1.8.7-p374/environment'" >&2
  exit 1
fi
