#!/usr/bin/env bash

if
  [[ -s "/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-2.1.2/environment" ]]
then
  source "/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-2.1.2/environment"
  exec unparser "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/abalonperin/dotfiles/rvm/rvm/gems/ruby-2.1.2/environment'" >&2
  exit 1
fi
