--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Gem::RemoteFetcher#configure_connection_for_https
is_singleton: false
name: configure_connection_for_https
params: (connection)
visibility: public
