#!/usr/bin/env bash

if
  [[ -s "/Users/abalonperin/dotfiles/rvm/rvm/gems/jruby-1.6.8/environment" ]]
then
  source "/Users/abalonperin/dotfiles/rvm/rvm/gems/jruby-1.6.8/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/abalonperin/dotfiles/rvm/rvm/gems/jruby-1.6.8/environment'" >&2
  exit 1
fi
